# Use this file to construct an environment
# for developing imglyb from source.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create -f dev-environment.yml
#   mamba activate imglyb-dev
#
# In addition to the dependencies needed for using imglyb, it
# includes tools for developer-related actions like running
# automated tests (pytest) and linting the code (black). If you
# want an environment without these tools, use environment.yml.

name: imglyb-dev
channels:
  - conda-forge
dependencies:
  - python >= 3.8
  # Project dependencies
  - jpype1
  - numpy
  - scyjava
  # Developer tools
  - autopep8
  - black
  - build
  - flake8
  - flake8-pyproject
  - isort
  - pytest
  - pytest-cov
  - toml
  # Project from source
  - pip
  - pip:
    - validate-pyproject[all]
    - -e '.'
