# Use this file to construct an environment for
# working with imglyb in a runtime environment.
#
# First, install mambaforge:
#
#   https://github.com/conda-forge/miniforge#mambaforge
#
# Then run:
#
#   mamba env create
#   mamba activate imglyb
#
# It includes the dependencies needed for using imglyb, but not tools
# for developer-related actions like running automated tests (pytest),
# linting the code (black), and generating the API documentation (sphinx).
# If you want an environment including these tools, use dev-environment.yml.

name: imglyb
channels:
  - conda-forge
dependencies:
  - python >= 3.7
  # Project dependencies
  - jpype1
  - numpy
  - scyjava
  # Project from source
  - pip
  - pip:
    - -e .
