name: build

on:
  push:
    branches:
      - main
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.python-version}}

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Set up uv
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv

    - name: Run tests
      shell: bash
      run: |
        bin/test.sh

    - name: Lint code
      shell: bash
      run: |
        bin/lint.sh
