name: build

on:
  push:
    branches:
      - master
    tags:
      - "*-[0-9]+.*"
  pull_request:
    branches:
      - master

jobs:
  build-cross-platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.10"]
        # Breaks due to https://github.com/jpype-project/jpype/issues/1009
        # Should be included once the fix is released
        exclude:
          - os: windows-latest
            python-version: "3.10"
        include:
          - os: windows-latest
            python-version: "3.9"

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v3
      with:
        python-version: ${{matrix.python-version}}

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Install pyimagej
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e ".[dev]"

    - name: Test ImageJ
      run: |
        python -m pytest -s -p no:faulthandler --color=yes
        echo "Done!"

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  conda-dev-test:
    name: Test Conda Development Setup And Code Coverage
    runs-on: ubuntu-latest
    defaults:
      # Steps that rely on the activated environment must be run with this shell setup.
      # See https://github.com/marketplace/actions/setup-miniconda#important
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          # Create env with dev packages
          auto-update-conda: true
          python-version: 3.9
          environment-file: dev-environment.yml
          # Activate imglyb-dev environment
          activate-environment: imglyb-dev
          auto-activate-base: false
          # Use mamba for faster setup
          use-mamba: true
          mamba-version: "*"
      - name: Test imglyb
        run: |
          python -m pytest tests/ -p no:faulthandler --cov-report=xml --cov=.
      # We could do this in its own action, but we'd have to setup the environment again.
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
